'''
Neuron simulator export for:

Components:
    null (Type: include)
    gap_junction0 (Type: gapJunction:  conductance=2.232032922E-9 (SI conductance))
    gap_junction1 (Type: gapJunction:  conductance=2.249178416E-9 (SI conductance))
    gap_junction2 (Type: gapJunction:  conductance=6.748015819E-9 (SI conductance))
    gap_junction3 (Type: gapJunction:  conductance=1.0430270059E-8 (SI conductance))
    gap_junction4 (Type: gapJunction:  conductance=5.720991436E-9 (SI conductance))
    gap_junction5 (Type: gapJunction:  conductance=1.2826737422E-8 (SI conductance))
    gap_junction6 (Type: gapJunction:  conductance=1.505518468E-9 (SI conductance))
    gap_junction7 (Type: gapJunction:  conductance=2.5630604739999996E-9 (SI conductance))
    gap_junction8 (Type: gapJunction:  conductance=1.2244350443E-8 (SI conductance))
    gap_junction9 (Type: gapJunction:  conductance=3.1721161259999997E-9 (SI conductance))
    gap_junction10 (Type: gapJunction:  conductance=5.122553387E-9 (SI conductance))
    gap_junction11 (Type: gapJunction:  conductance=6.380714794E-9 (SI conductance))
    gap_junction12 (Type: gapJunction:  conductance=1.326195729E-9 (SI conductance))
    gap_junction13 (Type: gapJunction:  conductance=7.389874054E-9 (SI conductance))
    gap_junction14 (Type: gapJunction:  conductance=2.139116597E-9 (SI conductance))
    gap_junction15 (Type: gapJunction:  conductance=1.9651426449999998E-9 (SI conductance))
    Input_0 (Type: pulseGenerator:  delay=0.02 (SI time) duration=0.2 (SI time) amplitude=4.0000000000000004E-11 (SI current))
    Input_1 (Type: pulseGenerator:  delay=0.22 (SI time) duration=0.2 (SI time) amplitude=-5.0000000000000005E-12 (SI current))
    Simple_Golgi_Net_network (Type: networkWithTemperature:  temperature=296.15 (SI temperature))
    null (Type: include)
    null (Type: include)
    null (Type: include)
    Very_Simple_Golgi_test_morph (Type: cell)
    null (Type: notes)
    Golgi_Na (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    Golgi_KV (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    LeakCond (Type: ionChannelPassive:  conductance=1.0E-11 (SI conductance))
    Simple_Golgi_Net (Type: Simulation:  length=0.45 (SI time) step=5.0E-6 (SI time))


    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.4.3
         org.neuroml.model   v1.4.3
         jLEMS               v0.9.8.1

'''

import neuron

import time
h = neuron.h
h.load_file("stdlib.hoc")

h.load_file("stdgui.hoc")

h("objref p")
h("p = new PythonObject()")

# Adding simulation Component(id=Simple_Golgi_Net type=Simulation) of network/component: Simple_Golgi_Net_network (Type: networkWithTemperature:  temperature=296.15 (SI temperature))

# Temperature used for network: 296.15 K
h.celsius = 296.15 - 273.15

print("Population Golgi_pop0 contains 4 instance(s) of component: Very_Simple_Golgi_test_morph of type: cell")

h.load_file("Very_Simple_Golgi_test_morph.hoc")
a_Golgi_pop0 = []
h("n_Golgi_pop0 = 4")
h("objectvar a_Golgi_pop0[n_Golgi_pop0]")
for i in range(int(h.n_Golgi_pop0)):
    h("a_Golgi_pop0[%i] = new Very_Simple_Golgi_test_morph()"%i)
    h("access a_Golgi_pop0[%i].Soma"%i)


h("proc initialiseV_Golgi_pop0() { for i = 0, n_Golgi_pop0-1 { a_Golgi_pop0[i].set_initial_v() } }")
h("objref fih_Golgi_pop0")
h('{fih_Golgi_pop0 = new FInitializeHandler(0, "initialiseV_Golgi_pop0()")}')

h("proc initialiseIons_Golgi_pop0() { for i = 0, n_Golgi_pop0-1 { a_Golgi_pop0[i].set_initial_ion_properties() } }")
h("objref fih_ion_Golgi_pop0")
h('{fih_ion_Golgi_pop0 = new FInitializeHandler(1, "initialiseIons_Golgi_pop0()")}')

print("Population Golgi_pop1 contains 4 instance(s) of component: Very_Simple_Golgi_test_morph of type: cell")

h.load_file("Very_Simple_Golgi_test_morph.hoc")
a_Golgi_pop1 = []
h("n_Golgi_pop1 = 4")
h("objectvar a_Golgi_pop1[n_Golgi_pop1]")
for i in range(int(h.n_Golgi_pop1)):
    h("a_Golgi_pop1[%i] = new Very_Simple_Golgi_test_morph()"%i)
    h("access a_Golgi_pop1[%i].Soma"%i)


h("proc initialiseV_Golgi_pop1() { for i = 0, n_Golgi_pop1-1 { a_Golgi_pop1[i].set_initial_v() } }")
h("objref fih_Golgi_pop1")
h('{fih_Golgi_pop1 = new FInitializeHandler(0, "initialiseV_Golgi_pop1()")}')

h("proc initialiseIons_Golgi_pop1() { for i = 0, n_Golgi_pop1-1 { a_Golgi_pop1[i].set_initial_ion_properties() } }")
h("objref fih_ion_Golgi_pop1")
h('{fih_ion_Golgi_pop1 = new FInitializeHandler(1, "initialiseIons_Golgi_pop1()")}')

'''
Adding projection: proj0
From Golgi_pop0 to Golgi_pop0 4 connection(s)
'''
h("objectvar syn_proj0_gap_junction0_A[4]")

h("objectvar syn_proj0_gap_junction0_B[4]")

h("a_Golgi_pop0[0].Section_1 { syn_proj0_gap_junction0_A[0] = new gap_junction0(0.885536) }")
h("a_Golgi_pop0[1].dend_1 { syn_proj0_gap_junction0_B[0] = new gap_junction0(0.578086) }")
h("setpointer syn_proj0_gap_junction0_A[0].vpeer, a_Golgi_pop0[1].dend_1.v(0.578086)")
h("setpointer syn_proj0_gap_junction0_B[0].vpeer, a_Golgi_pop0[0].Section_1.v(0.885536)")
h("a_Golgi_pop0[0].Section_3 { syn_proj0_gap_junction0_A[1] = new gap_junction0(0.873190) }")
h("a_Golgi_pop0[2].Section_1 { syn_proj0_gap_junction0_B[1] = new gap_junction0(0.216380) }")
h("setpointer syn_proj0_gap_junction0_A[1].vpeer, a_Golgi_pop0[2].Section_1.v(0.216380)")
h("setpointer syn_proj0_gap_junction0_B[1].vpeer, a_Golgi_pop0[0].Section_3.v(0.873190)")
h("a_Golgi_pop0[1].Section_1 { syn_proj0_gap_junction0_A[2] = new gap_junction0(0.983293) }")
h("a_Golgi_pop0[2].Section_1 { syn_proj0_gap_junction0_B[2] = new gap_junction0(0.832205) }")
h("setpointer syn_proj0_gap_junction0_A[2].vpeer, a_Golgi_pop0[2].Section_1.v(0.832205)")
h("setpointer syn_proj0_gap_junction0_B[2].vpeer, a_Golgi_pop0[1].Section_1.v(0.983293)")
h("a_Golgi_pop0[1].Section_1 { syn_proj0_gap_junction0_A[3] = new gap_junction0(0.078563) }")
h("a_Golgi_pop0[3].Section_3 { syn_proj0_gap_junction0_B[3] = new gap_junction0(0.994604) }")
h("setpointer syn_proj0_gap_junction0_A[3].vpeer, a_Golgi_pop0[3].Section_3.v(0.994604)")
h("setpointer syn_proj0_gap_junction0_B[3].vpeer, a_Golgi_pop0[1].Section_1.v(0.078563)")
'''
Adding projection: proj1
From Golgi_pop0 to Golgi_pop1 8 connection(s)
'''
h("objectvar syn_proj1_gap_junction4_A[8]")

h("objectvar syn_proj1_gap_junction4_B[8]")

h("a_Golgi_pop0[0].dend_1 { syn_proj1_gap_junction4_A[0] = new gap_junction4(0.626104) }")
h("a_Golgi_pop1[0].Section_1 { syn_proj1_gap_junction4_B[0] = new gap_junction4(0.325761) }")
h("setpointer syn_proj1_gap_junction4_A[0].vpeer, a_Golgi_pop1[0].Section_1.v(0.325761)")
h("setpointer syn_proj1_gap_junction4_B[0].vpeer, a_Golgi_pop0[0].dend_1.v(0.626104)")
h("a_Golgi_pop0[0].dend_1 { syn_proj1_gap_junction4_A[1] = new gap_junction4(0.164952) }")
h("a_Golgi_pop1[2].Section_1 { syn_proj1_gap_junction4_B[1] = new gap_junction4(0.967282) }")
h("setpointer syn_proj1_gap_junction4_A[1].vpeer, a_Golgi_pop1[2].Section_1.v(0.967282)")
h("setpointer syn_proj1_gap_junction4_B[1].vpeer, a_Golgi_pop0[0].dend_1.v(0.164952)")
h("a_Golgi_pop0[0].Section_1 { syn_proj1_gap_junction4_A[2] = new gap_junction4(0.496066) }")
h("a_Golgi_pop1[3].Section_1 { syn_proj1_gap_junction4_B[2] = new gap_junction4(0.184854) }")
h("setpointer syn_proj1_gap_junction4_A[2].vpeer, a_Golgi_pop1[3].Section_1.v(0.184854)")
h("setpointer syn_proj1_gap_junction4_B[2].vpeer, a_Golgi_pop0[0].Section_1.v(0.496066)")
h("a_Golgi_pop0[1].Section_3 { syn_proj1_gap_junction4_A[3] = new gap_junction4(0.416718) }")
h("a_Golgi_pop1[1].Section_3 { syn_proj1_gap_junction4_B[3] = new gap_junction4(0.243268) }")
h("setpointer syn_proj1_gap_junction4_A[3].vpeer, a_Golgi_pop1[1].Section_3.v(0.243268)")
h("setpointer syn_proj1_gap_junction4_B[3].vpeer, a_Golgi_pop0[1].Section_3.v(0.416718)")
h("a_Golgi_pop0[1].dend_1 { syn_proj1_gap_junction4_A[4] = new gap_junction4(0.413251) }")
h("a_Golgi_pop1[3].Section_1 { syn_proj1_gap_junction4_B[4] = new gap_junction4(0.691883) }")
h("setpointer syn_proj1_gap_junction4_A[4].vpeer, a_Golgi_pop1[3].Section_1.v(0.691883)")
h("setpointer syn_proj1_gap_junction4_B[4].vpeer, a_Golgi_pop0[1].dend_1.v(0.413251)")
h("a_Golgi_pop0[2].Section_1 { syn_proj1_gap_junction4_A[5] = new gap_junction4(0.893961) }")
h("a_Golgi_pop1[2].Section_1 { syn_proj1_gap_junction4_B[5] = new gap_junction4(0.330288) }")
h("setpointer syn_proj1_gap_junction4_A[5].vpeer, a_Golgi_pop1[2].Section_1.v(0.330288)")
h("setpointer syn_proj1_gap_junction4_B[5].vpeer, a_Golgi_pop0[2].Section_1.v(0.893961)")
h("a_Golgi_pop0[2].Section_1 { syn_proj1_gap_junction4_A[6] = new gap_junction4(0.363960) }")
h("a_Golgi_pop1[3].dend_1 { syn_proj1_gap_junction4_B[6] = new gap_junction4(0.516687) }")
h("setpointer syn_proj1_gap_junction4_A[6].vpeer, a_Golgi_pop1[3].dend_1.v(0.516687)")
h("setpointer syn_proj1_gap_junction4_B[6].vpeer, a_Golgi_pop0[2].Section_1.v(0.363960)")
h("a_Golgi_pop0[3].Section_1 { syn_proj1_gap_junction4_A[7] = new gap_junction4(0.685901) }")
h("a_Golgi_pop1[3].Section_3 { syn_proj1_gap_junction4_B[7] = new gap_junction4(0.401791) }")
h("setpointer syn_proj1_gap_junction4_A[7].vpeer, a_Golgi_pop1[3].Section_3.v(0.401791)")
h("setpointer syn_proj1_gap_junction4_B[7].vpeer, a_Golgi_pop0[3].Section_1.v(0.685901)")
'''
Adding projection: proj2
From Golgi_pop1 to Golgi_pop1 4 connection(s)
'''
h("objectvar syn_proj2_gap_junction12_A[4]")

h("objectvar syn_proj2_gap_junction12_B[4]")

h("a_Golgi_pop1[0].Section_1 { syn_proj2_gap_junction12_A[0] = new gap_junction12(0.920992) }")
h("a_Golgi_pop1[1].dend_1 { syn_proj2_gap_junction12_B[0] = new gap_junction12(0.676145) }")
h("setpointer syn_proj2_gap_junction12_A[0].vpeer, a_Golgi_pop1[1].dend_1.v(0.676145)")
h("setpointer syn_proj2_gap_junction12_B[0].vpeer, a_Golgi_pop1[0].Section_1.v(0.920992)")
h("a_Golgi_pop1[0].dend_1 { syn_proj2_gap_junction12_A[1] = new gap_junction12(0.349130) }")
h("a_Golgi_pop1[2].Section_1 { syn_proj2_gap_junction12_B[1] = new gap_junction12(0.901378) }")
h("setpointer syn_proj2_gap_junction12_A[1].vpeer, a_Golgi_pop1[2].Section_1.v(0.901378)")
h("setpointer syn_proj2_gap_junction12_B[1].vpeer, a_Golgi_pop1[0].dend_1.v(0.349130)")
h("a_Golgi_pop1[1].Section_1 { syn_proj2_gap_junction12_A[2] = new gap_junction12(0.232246) }")
h("a_Golgi_pop1[3].Section_3 { syn_proj2_gap_junction12_B[2] = new gap_junction12(0.424292) }")
h("setpointer syn_proj2_gap_junction12_A[2].vpeer, a_Golgi_pop1[3].Section_3.v(0.424292)")
h("setpointer syn_proj2_gap_junction12_B[2].vpeer, a_Golgi_pop1[1].Section_1.v(0.232246)")
h("a_Golgi_pop1[2].Section_1 { syn_proj2_gap_junction12_A[3] = new gap_junction12(0.099616) }")
h("a_Golgi_pop1[3].Section_1 { syn_proj2_gap_junction12_B[3] = new gap_junction12(0.148515) }")
h("setpointer syn_proj2_gap_junction12_A[3].vpeer, a_Golgi_pop1[3].Section_1.v(0.148515)")
h("setpointer syn_proj2_gap_junction12_B[3].vpeer, a_Golgi_pop1[2].Section_1.v(0.099616)")
# Adding input: Component(id=null type=explicitInput)

h("objectvar explicitInput_Input_0_Golgi_pop0_1_a_Golgi_pop01_Soma")
h("a_Golgi_pop0[1].Soma { explicitInput_Input_0_Golgi_pop0_1_a_Golgi_pop01_Soma = new Input_0(0.5) } ")

# Adding input: Component(id=null type=explicitInput)

h("objectvar explicitInput_Input_1_Golgi_pop0_1_a_Golgi_pop01_Soma")
h("a_Golgi_pop0[1].Soma { explicitInput_Input_1_Golgi_pop0_1_a_Golgi_pop01_Soma = new Input_1(0.5) } ")

# Adding input: Component(id=null type=explicitInput)

h("objectvar explicitInput_Input_0_Golgi_pop0_2_a_Golgi_pop02_Soma")
h("a_Golgi_pop0[2].Soma { explicitInput_Input_0_Golgi_pop0_2_a_Golgi_pop02_Soma = new Input_0(0.5) } ")

# Adding input: Component(id=null type=explicitInput)

h("objectvar explicitInput_Input_1_Golgi_pop0_2_a_Golgi_pop02_Soma")
h("a_Golgi_pop0[2].Soma { explicitInput_Input_1_Golgi_pop0_2_a_Golgi_pop02_Soma = new Input_1(0.5) } ")

# Adding input: Component(id=null type=explicitInput)

h("objectvar explicitInput_Input_0_Golgi_pop1_3_a_Golgi_pop13_Soma")
h("a_Golgi_pop1[3].Soma { explicitInput_Input_0_Golgi_pop1_3_a_Golgi_pop13_Soma = new Input_0(0.5) } ")

# Adding input: Component(id=null type=explicitInput)

h("objectvar explicitInput_Input_1_Golgi_pop1_3_a_Golgi_pop13_Soma")
h("a_Golgi_pop1[3].Soma { explicitInput_Input_1_Golgi_pop1_3_a_Golgi_pop13_Soma = new Input_1(0.5) } ")

# Adding input: Component(id=null type=explicitInput)

h("objectvar explicitInput_Input_0_Golgi_pop1_2_a_Golgi_pop12_Soma")
h("a_Golgi_pop1[2].Soma { explicitInput_Input_0_Golgi_pop1_2_a_Golgi_pop12_Soma = new Input_0(0.5) } ")

# Adding input: Component(id=null type=explicitInput)

h("objectvar explicitInput_Input_1_Golgi_pop1_2_a_Golgi_pop12_Soma")
h("a_Golgi_pop1[2].Soma { explicitInput_Input_1_Golgi_pop1_2_a_Golgi_pop12_Soma = new Input_1(0.5) } ")

trec = h.Vector()
trec.record(h._ref_t)

h.tstop = 450

h.dt = 0.005

h.steps_per_ms = 200.0



# File to save: time
# Column: time
h(' objectvar v_time ')
h(' { v_time = new Vector() } ')
h(' v_time.record(&t) ')
h.v_time.resize((h.tstop * h.steps_per_ms) + 1)

# File to save: Volts1_file0_2
# Column: Golgi_pop1[2]/v
h(' objectvar v_v2_Volts1_file0_2 ')
h(' { v_v2_Volts1_file0_2 = new Vector() } ')
h(' v_v2_Volts1_file0_2.record(&a_Golgi_pop1[2].Soma.v(0.5)) ')
h.v_v2_Volts1_file0_2.resize((h.tstop * h.steps_per_ms) + 1)

# File to save: Volts1_file0_1
# Column: Golgi_pop1[1]/v
h(' objectvar v_v1_Volts1_file0_1 ')
h(' { v_v1_Volts1_file0_1 = new Vector() } ')
h(' v_v1_Volts1_file0_1.record(&a_Golgi_pop1[1].Soma.v(0.5)) ')
h.v_v1_Volts1_file0_1.resize((h.tstop * h.steps_per_ms) + 1)

# File to save: Volts1_file0_0
# Column: Golgi_pop1[0]/v
h(' objectvar v_v0_Volts1_file0_0 ')
h(' { v_v0_Volts1_file0_0 = new Vector() } ')
h(' v_v0_Volts1_file0_0.record(&a_Golgi_pop1[0].Soma.v(0.5)) ')
h.v_v0_Volts1_file0_0.resize((h.tstop * h.steps_per_ms) + 1)

# File to save: Volts1_file0_3
# Column: Golgi_pop1[3]/v
h(' objectvar v_v3_Volts1_file0_3 ')
h(' { v_v3_Volts1_file0_3 = new Vector() } ')
h(' v_v3_Volts1_file0_3.record(&a_Golgi_pop1[3].Soma.v(0.5)) ')
h.v_v3_Volts1_file0_3.resize((h.tstop * h.steps_per_ms) + 1)

# File to save: Volts0_file0_0
# Column: Golgi_pop0[0]/v
h(' objectvar v_v0_Volts0_file0_0 ')
h(' { v_v0_Volts0_file0_0 = new Vector() } ')
h(' v_v0_Volts0_file0_0.record(&a_Golgi_pop0[0].Soma.v(0.5)) ')
h.v_v0_Volts0_file0_0.resize((h.tstop * h.steps_per_ms) + 1)

# File to save: Volts0_file0_1
# Column: Golgi_pop0[1]/v
h(' objectvar v_v1_Volts0_file0_1 ')
h(' { v_v1_Volts0_file0_1 = new Vector() } ')
h(' v_v1_Volts0_file0_1.record(&a_Golgi_pop0[1].Soma.v(0.5)) ')
h.v_v1_Volts0_file0_1.resize((h.tstop * h.steps_per_ms) + 1)

# File to save: Volts0_file0_2
# Column: Golgi_pop0[2]/v
h(' objectvar v_v2_Volts0_file0_2 ')
h(' { v_v2_Volts0_file0_2 = new Vector() } ')
h(' v_v2_Volts0_file0_2.record(&a_Golgi_pop0[2].Soma.v(0.5)) ')
h.v_v2_Volts0_file0_2.resize((h.tstop * h.steps_per_ms) + 1)

# File to save: Volts0_file0_3
# Column: Golgi_pop0[3]/v
h(' objectvar v_v3_Volts0_file0_3 ')
h(' { v_v3_Volts0_file0_3 = new Vector() } ')
h(' v_v3_Volts0_file0_3.record(&a_Golgi_pop0[3].Soma.v(0.5)) ')
h.v_v3_Volts0_file0_3.resize((h.tstop * h.steps_per_ms) + 1)



sim_start = time.time()
print("Running a simulation of %sms (dt = %sms)" % (h.tstop, h.dt))

h.run()

sim_end = time.time()
sim_time = sim_end - sim_start
print("Finished simulation in %f seconds (%f mins), saving results..."%(sim_time, sim_time/60.0))


# File to save: time
py_v_time = [ t/1000 for t in h.v_time.to_python() ]  # Convert to Python list for speed...

f_time_f2 = open('time.dat', 'w')
for i in range(int(h.tstop * h.steps_per_ms) + 1):
    f_time_f2.write('%f'% py_v_time[i])  # Save in SI units...+ '\n')
f_time_f2.close()
print("Saved data to: time.dat")

# File to save: Volts1_file0_2
py_v_v2_Volts1_file0_2 = [ float(x  / 1000.0) for x in h.v_v2_Volts1_file0_2.to_python() ]  # Convert to Python list for speed, variable has dim: voltage

f_Volts1_file0_2_f2 = open('simulations/V2010multi1_2c_1input/sim0/Golgi_pop1_cell2.dat', 'w')
for i in range(int(h.tstop * h.steps_per_ms) + 1):
    f_Volts1_file0_2_f2.write('%e\t'% py_v_time[i]  + '%e\t'%(py_v_v2_Volts1_file0_2[i]) + '\n')
f_Volts1_file0_2_f2.close()
print("Saved data to: simulations/V2010multi1_2c_1input/sim0/Golgi_pop1_cell2.dat")

# File to save: Volts1_file0_1
py_v_v1_Volts1_file0_1 = [ float(x  / 1000.0) for x in h.v_v1_Volts1_file0_1.to_python() ]  # Convert to Python list for speed, variable has dim: voltage

f_Volts1_file0_1_f2 = open('simulations/V2010multi1_2c_1input/sim0/Golgi_pop1_cell1.dat', 'w')
for i in range(int(h.tstop * h.steps_per_ms) + 1):
    f_Volts1_file0_1_f2.write('%e\t'% py_v_time[i]  + '%e\t'%(py_v_v1_Volts1_file0_1[i]) + '\n')
f_Volts1_file0_1_f2.close()
print("Saved data to: simulations/V2010multi1_2c_1input/sim0/Golgi_pop1_cell1.dat")

# File to save: Volts1_file0_0
py_v_v0_Volts1_file0_0 = [ float(x  / 1000.0) for x in h.v_v0_Volts1_file0_0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage

f_Volts1_file0_0_f2 = open('simulations/V2010multi1_2c_1input/sim0/Golgi_pop1_cell0.dat', 'w')
for i in range(int(h.tstop * h.steps_per_ms) + 1):
    f_Volts1_file0_0_f2.write('%e\t'% py_v_time[i]  + '%e\t'%(py_v_v0_Volts1_file0_0[i]) + '\n')
f_Volts1_file0_0_f2.close()
print("Saved data to: simulations/V2010multi1_2c_1input/sim0/Golgi_pop1_cell0.dat")

# File to save: Volts1_file0_3
py_v_v3_Volts1_file0_3 = [ float(x  / 1000.0) for x in h.v_v3_Volts1_file0_3.to_python() ]  # Convert to Python list for speed, variable has dim: voltage

f_Volts1_file0_3_f2 = open('simulations/V2010multi1_2c_1input/sim0/Golgi_pop1_cell3.dat', 'w')
for i in range(int(h.tstop * h.steps_per_ms) + 1):
    f_Volts1_file0_3_f2.write('%e\t'% py_v_time[i]  + '%e\t'%(py_v_v3_Volts1_file0_3[i]) + '\n')
f_Volts1_file0_3_f2.close()
print("Saved data to: simulations/V2010multi1_2c_1input/sim0/Golgi_pop1_cell3.dat")

# File to save: Volts0_file0_0
py_v_v0_Volts0_file0_0 = [ float(x  / 1000.0) for x in h.v_v0_Volts0_file0_0.to_python() ]  # Convert to Python list for speed, variable has dim: voltage

f_Volts0_file0_0_f2 = open('simulations/V2010multi1_2c_1input/sim0/Golgi_pop0_cell0.dat', 'w')
for i in range(int(h.tstop * h.steps_per_ms) + 1):
    f_Volts0_file0_0_f2.write('%e\t'% py_v_time[i]  + '%e\t'%(py_v_v0_Volts0_file0_0[i]) + '\n')
f_Volts0_file0_0_f2.close()
print("Saved data to: simulations/V2010multi1_2c_1input/sim0/Golgi_pop0_cell0.dat")

# File to save: Volts0_file0_1
py_v_v1_Volts0_file0_1 = [ float(x  / 1000.0) for x in h.v_v1_Volts0_file0_1.to_python() ]  # Convert to Python list for speed, variable has dim: voltage

f_Volts0_file0_1_f2 = open('simulations/V2010multi1_2c_1input/sim0/Golgi_pop0_cell1.dat', 'w')
for i in range(int(h.tstop * h.steps_per_ms) + 1):
    f_Volts0_file0_1_f2.write('%e\t'% py_v_time[i]  + '%e\t'%(py_v_v1_Volts0_file0_1[i]) + '\n')
f_Volts0_file0_1_f2.close()
print("Saved data to: simulations/V2010multi1_2c_1input/sim0/Golgi_pop0_cell1.dat")

# File to save: Volts0_file0_2
py_v_v2_Volts0_file0_2 = [ float(x  / 1000.0) for x in h.v_v2_Volts0_file0_2.to_python() ]  # Convert to Python list for speed, variable has dim: voltage

f_Volts0_file0_2_f2 = open('simulations/V2010multi1_2c_1input/sim0/Golgi_pop0_cell2.dat', 'w')
for i in range(int(h.tstop * h.steps_per_ms) + 1):
    f_Volts0_file0_2_f2.write('%e\t'% py_v_time[i]  + '%e\t'%(py_v_v2_Volts0_file0_2[i]) + '\n')
f_Volts0_file0_2_f2.close()
print("Saved data to: simulations/V2010multi1_2c_1input/sim0/Golgi_pop0_cell2.dat")

# File to save: Volts0_file0_3
py_v_v3_Volts0_file0_3 = [ float(x  / 1000.0) for x in h.v_v3_Volts0_file0_3.to_python() ]  # Convert to Python list for speed, variable has dim: voltage

f_Volts0_file0_3_f2 = open('simulations/V2010multi1_2c_1input/sim0/Golgi_pop0_cell3.dat', 'w')
for i in range(int(h.tstop * h.steps_per_ms) + 1):
    f_Volts0_file0_3_f2.write('%e\t'% py_v_time[i]  + '%e\t'%(py_v_v3_Volts0_file0_3[i]) + '\n')
f_Volts0_file0_3_f2.close()
print("Saved data to: simulations/V2010multi1_2c_1input/sim0/Golgi_pop0_cell3.dat")

save_end = time.time()
save_time = save_end - sim_end
print("Finished saving results in %f seconds"%(save_time))

print("Done")

quit()
